### ISSUE TITLE
No Eq instance for Haskus.Utils.Variant.VEither

### ISSUE THREAD

**Issue by frabbit** [haskus/packages#41]
Is there any reason why there is no Eq instance for `Haskus.Utils.Variant.VEither`?

I'm currently using this Orphan:

```hs
instance ( Eq a, Eq (V es)) => Eq (VEither es a) where
  (==) (VLeft as) (VLeft bs) =  as == bs
  (==) (VRight a) (VRight b) = a == b
  (==) _ _ = False
```

If there are no arguments against it, i can create a PR for this.

**Comment by hsyl20** [comment]
No particular reason. Both `Eq` and `Ord` instances could be `newtype` derived to benefit from the optimized implementation for `Variant`. PR welcome :)

**Comment by frabbit** [comment]
There you go: https://github.com/haskus/packages/pull/42/commits

**Comment by hsyl20** [comment]
Thanks, merged! I'll make a Hackage release soon
